githubRepoOwner: Ahmed-CIO
githubRepoName: TestRepo
githubHost: github.com
githubRemote: origin
githubBranch: main
requireChecks: true
requireApproval: true
mergeMethod: squash
mergeQueue: false
forceFetchTags: false
showPrTitlesInStack: false
branchPushIndividually: false
createDraftPRs: true